timestamp,symbol,order,volume
2025-04-06 13:59:00,US30,BUY,1
2025-04-06 14:01:00,US30,BUY,1
2025-04-06 14:03:00,US30,BUY,1
2025-04-06 14:06:00,US30,BUY,1
2025-04-06 14:07:00,US30,BUY,1
2025-04-06 14:08:00,US30,BUY,1
2025-04-06 14:09:00,US30,BUY,1
2025-04-06 14:10:01,US30,BUY,1
2025-04-06 14:11:00,US30,BUY,1
2025-04-06 14:12:00,US30,BUY,1
2025-04-06 14:13:00,US30,BUY,1
2025-04-06 14:14:00,US30,BUY,1
2025-04-06 14:19:00,US30,BUY,1
2025-04-06 14:24:00,US30,BUY,1
2025-04-06 15:10:01,US 30,SELL,1
2025-04-06 15:11:00,US 30,SELL,1
2025-04-06 15:12:01,US 30,SELL,1
2025-04-06 15:13:00,US 30,SELL,1
2025-04-06 15:14:00,US 30,BUY,1
2025-04-06 15:15:00,US 30,BUY,1
2025-04-06 15:16:00,US 30,BUY,1
2025-04-06 15:17:00,US 30,SELL,1
2025-04-06 15:18:00,US 30,BUY,1
2025-04-06 15:19:00,US 30,SELL,1
2025-04-06 15:20:00,US 30,SELL,1
2025-04-06 15:21:00,US 30,SELL,1
2025-04-06 15:22:00,US 30,SELL,1
2025-04-06 15:23:01,US 30,BUY,1
2025-04-06 15:24:00,US 30,SELL,1
2025-04-06 15:25:00,US 30,BUY,1
2025-04-06 15:26:00,US 30,SELL,1
2025-04-06 15:27:00,US 30,SELL,1
2025-04-06 15:28:00,US 30,BUY,1
2025-04-06 16:13:11,US 30,SELL,1
2025-04-06 16:14:01,US 30,BUY,1
2025-04-06 16:15:01,US 30,SELL,1
2025-04-06 16:16:00,US 30,BUY,1
2025-04-06 16:17:00,US 30,BUY,1
2025-04-06 16:21:16,US 30,SELL,1
2025-04-06 16:22:00,US 30,BUY,1
2025-04-06 16:23:00,US 30,SELL,1
2025-04-06 16:24:00,US 30,BUY,1
2025-04-06 16:25:00,US 30,BUY,1
2025-04-06 16:26:00,US 30,BUY,1
2025-04-06 16:27:01,US 30,SELL,1
2025-04-06 16:28:00,US 30,BUY,1
2025-04-06 16:30:20,US 30,SELL,1
2025-04-06 16:31:00,US 30,BUY,1
2025-04-06 16:32:00,US 30,BUY,1
2025-04-06 16:33:00,US 30,SELL,1
2025-04-06 16:34:00,US 30,SELL,1
2025-04-06 16:35:01,US 30,SELL,1
2025-04-06 16:36:01,US 30,SELL,1
2025-04-06 16:37:00,US 30,BUY,1
2025-04-06 16:38:00,US 30,SELL,1
2025-04-06 16:39:00,US 30,SELL,1
2025-04-06 16:40:01,US 30,BUY,1
2025-04-06 16:41:00,US 30,SELL,1
2025-04-06 16:42:00,US 30,SELL,1
2025-04-06 16:43:01,US 30,SELL,1
2025-04-06 16:44:00,US 30,SELL,1
2025-04-06 16:45:01,US 30,SELL,1
2025-04-06 16:46:01,US 30,SELL,1
2025-04-06 16:47:00,US 30,SELL,1
2025-04-06 16:48:00,US 30,BUY,1
2025-04-06 16:49:00,US 30,BUY,1
2025-04-06 16:50:01,US 30,BUY,1
2025-04-06 16:51:00,US 30,SELL,1
2025-04-06 16:52:00,US 30,SELL,1
2025-04-06 16:53:01,US 30,BUY,1
2025-04-06 16:54:00,US 30,SELL,1
2025-04-06 16:55:00,US 30,BUY,1
2025-04-06 16:56:00,US 30,SELL,1
2025-04-06 16:57:00,US 30,SELL,1
2025-04-06 16:58:00,US 30,SELL,1
2025-04-06 16:59:00,US 30,SELL,1
2025-04-06 17:00:01,US 30,SELL,1
2025-04-06 17:01:00,US 30,SELL,1
2025-04-06 17:02:00,US 30,BUY,1
2025-04-06 17:03:00,US 30,SELL,1
2025-04-06 17:04:00,US 30,SELL,1
2025-04-06 17:05:01,US 30,BUY,1
2025-04-06 17:06:01,US 30,SELL,1
2025-04-06 17:07:01,US 30,SELL,1
2025-04-06 17:08:00,US 30,BUY,1
2025-04-06 17:09:00,US 30,BUY,1
2025-04-06 17:10:00,US 30,BUY,1
2025-04-06 17:11:00,US 30,SELL,1
2025-04-06 17:12:00,US 30,SELL,1
2025-04-06 17:13:00,US 30,SELL,1
2025-04-06 17:14:00,US 30,SELL,1
2025-04-06 17:15:01,US 30,SELL,1
2025-04-06 17:16:00,US 30,SELL,1
2025-04-06 17:17:00,US 30,BUY,1
2025-04-06 17:18:00,US 30,SELL,1
2025-04-06 17:19:00,US 30,BUY,1
2025-04-06 17:20:01,US 30,BUY,1
2025-04-06 17:21:00,US 30,BUY,1
2025-04-06 17:22:00,US 30,SELL,1
2025-04-06 17:23:00,US 30,SELL,1
2025-04-06 17:24:00,US 30,BUY,1
2025-04-06 17:25:00,US 30,SELL,1
2025-04-06 17:26:00,US 30,SELL,1
2025-04-06 17:27:00,US 30,SELL,1
2025-04-06 17:28:00,US 30,SELL,1
2025-04-06 17:29:00,US 30,BUY,1
2025-04-06 17:30:00,US 30,BUY,1
2025-04-06 17:31:00,US 30,SELL,1
2025-04-06 17:32:00,US 30,SELL,1
2025-04-06 17:33:00,US 30,SELL,1
2025-04-06 17:34:00,US 30,SELL,1
2025-04-06 17:35:00,US 30,BUY,1
2025-04-06 17:36:01,US 30,SELL,1
2025-04-06 17:37:00,US 30,BUY,1
2025-04-06 17:38:00,US 30,SELL,1
2025-04-06 17:39:00,US 30,BUY,1
2025-04-06 17:40:00,US 30,BUY,1
2025-04-06 17:41:00,US 30,SELL,1
2025-04-06 17:42:00,US 30,SELL,1
2025-04-06 17:43:00,US 30,SELL,1
2025-04-06 17:44:01,US 30,SELL,1
2025-04-06 17:45:01,US 30,SELL,1
2025-04-06 17:46:01,US 30,SELL,1
2025-04-06 17:47:00,US 30,BUY,1
2025-04-06 17:48:00,US 30,SELL,1
2025-04-06 17:49:00,US 30,BUY,1
2025-04-06 17:50:00,US 30,SELL,1
2025-04-06 17:51:00,US 30,SELL,1
2025-04-06 17:52:00,US 30,SELL,1
2025-04-06 17:53:00,US 30,SELL,1
2025-04-06 17:54:00,US 30,SELL,1
2025-04-06 17:55:00,US 30,SELL,1
2025-04-06 17:56:00,US 30,SELL,1
2025-04-06 17:57:00,US 30,BUY,1
2025-04-06 17:58:00,US 30,SELL,1
2025-04-06 17:59:00,US 30,SELL,1
2025-04-06 18:00:02,US 30,BUY,1
2025-04-06 18:01:01,US 30,SELL,1
2025-04-12T12:51:36.954527+00:00,BTCUSD,SELL,1,fake-order-id-123456
2025-04-12T12:52:01.087195+00:00,BTCUSD,SELL,1,fake-order-id-123456
2025-04-12T12:53:03.361981+00:00,BTCUSD,BUY,1,fake-order-id-123456
2025-04-12T12:54:02.786731+00:00,BTCUSD,BUY,1,fake-order-id-123456
2025-04-12T12:55:01.161288+00:00,BTCUSD,SELL,1,fake-order-id-123456
2025-04-12T12:56:12.024488+00:00,BTCUSD,BUY,1,fake-order-id-123456
2025-04-12T12:57:01.080358+00:00,BTCUSD,SELL,1,fake-order-id-123456
2025-04-12T12:58:01.057235+00:00,BTCUSD,SELL,1,fake-order-id-123456
2025-04-12T12:59:00.892524+00:00,BTCUSD,BUY,1,fake-order-id-123456
2025-04-12T13:00:03.216126+00:00,BTCUSD,SELL,1,fake-order-id-123456
2025-04-12T13:01:05.153328+00:00,BTCUSD,SELL,1,fake-order-id-123456
2025-04-12T14:43:00.741123+00:00,BTCUSD,BUY,1,-
2025-04-12T14:44:00.998378+00:00,BTCUSD,SELL,1,-
2025-04-12T14:45:02.122286+00:00,BTCUSD,SELL,1,-
2025-04-12T14:46:01.965811+00:00,BTCUSD,SELL,1,-
2025-04-12T14:57:00.830344+00:00,BTCUSD,BUY,100000,-
2025-04-12T14:58:00.758552+00:00,BTCUSD,SELL,100000,-
2025-04-12T14:59:01.304247+00:00,BTCUSD,SELL,100000,-
2025-04-12T15:00:04.974413+00:00,BTCUSD,SELL,100000,-
2025-04-12T15:01:01.021987+00:00,BTCUSD,BUY,100000,-
2025-04-12T15:02:00.774820+00:00,BTCUSD,BUY,100000,-
2025-04-12T15:03:01.147875+00:00,BTCUSD,BUY,100000,-
2025-04-12T15:04:01.138178+00:00,BTCUSD,SELL,100000,-
2025-04-12T15:07:17.586508+00:00,BTCUSD,SELL,100000,-
2025-04-12T15:08:01.509290+00:00,BTCUSD,SELL,100000,-
2025-04-12T15:09:01.311737+00:00,BTCUSD,SELL,100000,-
2025-04-12T15:10:03.289182+00:00,BTCUSD,BUY,100000,-
2025-04-12T15:11:01.022476+00:00,BTCUSD,BUY,1,-
2025-04-12T15:12:01.858876+00:00,BTCUSD,BUY,1,-
2025-04-12T15:13:00.970718+00:00,BTCUSD,SELL,1,-
2025-04-12T15:14:01.371172+00:00,BTCUSD,SELL,1,-
2025-04-12T15:15:03.047860+00:00,BTCUSD,BUY,1,-
2025-04-12T15:16:00.745303+00:00,BTCUSD,BUY,1,-
2025-04-12T15:17:00.841990+00:00,BTCUSD,BUY,1,-
2025-04-12T15:18:00.973851+00:00,BTCUSD,SELL,1,-
2025-04-12T15:19:00.787041+00:00,BTCUSD,BUY,1,-
2025-04-12T15:20:00.681149+00:00,BTCUSD,BUY,100000000,-
2025-04-12T15:21:00.795659+00:00,BTCUSD,BUY,100000000,-
2025-04-12T15:22:00.904141+00:00,BTCUSD,SELL,100000000,-
2025-04-12T15:23:00.816784+00:00,BTCUSD,SELL,100000000,-
2025-04-12T15:24:01.131061+00:00,BTCUSD,SELL,100000000,-
2025-04-12T15:25:00.933490+00:00,BTCUSD,BUY,100000000,-
2025-04-12T15:26:01.192336+00:00,BTCUSD,SELL,100000000,-
2025-04-12T15:27:01.269205+00:00,BTCUSD,SELL,100000000,-
2025-04-12T15:28:01.385904+00:00,BTCUSD,BUY,100000000,-
2025-04-12T15:29:01.109369+00:00,BTCUSD,BUY,100000000,-
2025-04-12T15:30:05.141145+00:00,BTCUSD,SELL,100000000,-
2025-04-12T15:31:00.927835+00:00,BTCUSD,BUY,100000000,-
2025-04-12T15:32:01.943351+00:00,BTCUSD,BUY,100000000,-
2025-04-12T15:33:04.537295+00:00,BTCUSD,BUY,100000000,-
2025-04-12T15:34:02.576455+00:00,BTCUSD,BUY,100000000,-
2025-04-12T15:35:00.803983+00:00,BTCUSD,BUY,100000,-
2025-04-12T15:36:02.589839+00:00,BTCUSD,SELL,100000,-
2025-04-12T15:37:01.092813+00:00,BTCUSD,BUY,100000,-
2025-04-12T15:38:01.174336+00:00,BTCUSD,BUY,100000,-
2025-04-12T15:39:01.036179+00:00,BTCUSD,SELL,100000,-
2025-04-12T15:40:01.233309+00:00,BTCUSD,SELL,100000,-
2025-04-12T15:44:12.034142+00:00,BTCUSD,BUY,100000,-
2025-04-12T15:45:01.856401+00:00,BTCUSD,SELL,100000,-
2025-04-12T15:46:01.414919+00:00,BTCUSD,BUY,100000,-
2025-04-12T15:47:00.928322+00:00,BTCUSD,SELL,100000,-
2025-04-12T15:48:01.041844+00:00,BTCUSD,SELL,1,-
2025-04-12T15:49:04.897231+00:00,BTCUSD,SELL,1,-
2025-04-12T15:50:02.881322+00:00,BTCUSD,SELL,1,-
2025-04-12T15:51:00.928353+00:00,BTCUSD,SELL,1,-
2025-04-12T15:52:00.992651+00:00,BTCUSD,BUY,1,-
2025-04-12T15:53:00.616247+00:00,BTCUSD,SELL,1,-
2025-04-12T15:54:00.981830+00:00,BTCUSD,BUY,1,-
2025-04-12T15:55:01.339063+00:00,BTCUSD,SELL,1,-
2025-04-12T15:56:01.994424+00:00,BTCUSD,SELL,1,-
2025-04-12T15:57:01.698758+00:00,BTCUSD,SELL,1,-
2025-04-12T15:58:04.472033+00:00,BTCUSD,SELL,1,-
2025-04-12T15:59:01.600597+00:00,BTCUSD,SELL,1,-
2025-04-12T16:00:03.737924+00:00,BTCUSD,SELL,1,-
2025-04-12T16:01:01.562939+00:00,BTCUSD,BUY,1,-
2025-04-12T16:02:01.356803+00:00,BTCUSD,BUY,1,-
2025-04-12T16:03:01.159911+00:00,BTCUSD,BUY,1,-
2025-04-12T16:04:00.813656+00:00,BTCUSD,BUY,1,-
2025-04-12T16:05:00.946640+00:00,BTCUSD,SELL,1,-
2025-04-12T16:06:00.861410+00:00,BTCUSD,SELL,1,-
2025-04-12T16:07:01.032084+00:00,BTCUSD,SELL,1,-
2025-04-12T16:08:00.641924+00:00,BTCUSD,SELL,1,-
2025-04-12T16:10:00.890495+00:00,BTCUSD,BUY,1,-
2025-04-12T16:11:01.247442+00:00,BTCUSD,SELL,1,-
2025-04-12T16:12:01.123266+00:00,BTCUSD,BUY,1,-
2025-04-12T16:13:01.166293+00:00,BTCUSD,SELL,1,-
2025-04-12T16:14:00.829908+00:00,BTCUSD,BUY,1,-
2025-04-12T16:15:00.622197+00:00,BTCUSD,BUY,1,-
2025-04-12T16:16:01.345144+00:00,BTCUSD,SELL,1,-
2025-04-12T16:17:01.048400+00:00,BTCUSD,BUY,1,-
2025-04-12T16:18:02.370365+00:00,BTCUSD,BUY,1,-
2025-04-12T16:19:01.143069+00:00,BTCUSD,BUY,1,-
2025-04-12T16:20:01.016390+00:00,BTCUSD,SELL,1,-
2025-04-12T16:21:00.905631+00:00,BTCUSD,BUY,1,-
2025-04-12T16:22:00.893155+00:00,BTCUSD,BUY,1,-
2025-04-12T16:23:00.793054+00:00,BTCUSD,BUY,1,-
2025-04-12T16:24:00.828661+00:00,BTCUSD,BUY,1,-
2025-04-12T16:25:01.030165+00:00,BTCUSD,SELL,1,-
2025-04-12T16:26:01.045593+00:00,BTCUSD,SELL,1,-
2025-04-12T16:27:01.935824+00:00,BTCUSD,SELL,1,-
2025-04-12T16:28:01.052767+00:00,BTCUSD,SELL,1,-
2025-04-12T18:25:01.000220+00:00,BTCUSD,BUY,1,-
2025-04-12T18:26:00.999405+00:00,BTCUSD,SELL,1,-
2025-04-12T18:27:00.997965+00:00,BTCUSD,BUY,1,-
2025-04-12T18:28:00.701949+00:00,BTCUSD,BUY,1,-
2025-04-12T18:29:00.726137+00:00,BTCUSD,BUY,1,-
2025-04-12T18:30:07.018258+00:00,BTCUSD,BUY,1,-
2025-04-12T18:31:01.217859+00:00,BTCUSD,SELL,1,-
2025-04-12T18:32:02.620258+00:00,BTCUSD,SELL,1,-
2025-04-12T18:33:00.580221+00:00,BTCUSD,BUY,1,-
2025-04-12T18:34:01.025720+00:00,BTCUSD,BUY,1,-
2025-04-12T18:35:00.983225+00:00,BTCUSD,BUY,1,-
2025-04-12T18:40:00.937848+00:00,BTCUSD,BUY,1,-
2025-04-12T18:41:04.082930+00:00,BTCUSD,BUY,1,-
2025-04-12T18:42:01.425897+00:00,BTCUSD,BUY,1,-
2025-04-12T18:43:01.865260+00:00,BTCUSD,BUY,1,-
2025-04-12T18:44:01.105114+00:00,BTCUSD,BUY,1,-
2025-04-12T19:04:06.750158+00:00,BTCUSD,SELL,1,-
2025-04-12T19:05:00.757502+00:00,BTCUSD,BUY,1,-
2025-04-12T19:06:00.917582+00:00,BTCUSD,BUY,1,-
2025-04-12T19:07:00.818887+00:00,BTCUSD,BUY,1,-
2025-04-12T19:09:01.260844+00:00,BTCUSD,SELL,1,SUCCESS
2025-04-12T19:10:01.261108+00:00,BTCUSD,BUY,1,SUCCESS
2025-04-12T19:11:01.261149+00:00,BTCUSD,SELL,1,SUCCESS
2025-04-12T19:12:01.261444+00:00,BTCUSD,SELL,1,SUCCESS
2025-04-12T19:13:01.260926+00:00,BTCUSD,SELL,1,SUCCESS
2025-04-12T19:14:02.261277+00:00,BTCUSD,BUY,1,SUCCESS
2025-04-12T19:15:01.261499+00:00,BTCUSD,SELL,1,SUCCESS
2025-04-12T19:16:02.261180+00:00,BTCUSD,SELL,1,SUCCESS
2025-04-12T19:17:02.260973+00:00,BTCUSD,SELL,1,SUCCESS
2025-04-12T19:18:02.261142+00:00,BTCUSD,BUY,1,SUCCESS
2025-04-12T19:19:01.260503+00:00,BTCUSD,BUY,1,SUCCESS
2025-04-12T19:21:01.260412+00:00,BTCUSD,SELL,100,SUCCESS
2025-04-12T19:22:03.260266+00:00,BTCUSD,BUY,100,SUCCESS
2025-04-12T19:23:01.261187+00:00,BTCUSD,SELL,100,SUCCESS
2025-04-12T19:24:01.261180+00:00,BTCUSD,SELL,100,SUCCESS
2025-04-12T19:25:02.261087+00:00,BTCUSD,BUY,100,SUCCESS
2025-04-12T19:26:01.260347+00:00,BTCUSD,BUY,100,SUCCESS
2025-04-12T19:27:01.260493+00:00,BTCUSD,SELL,100,SUCCESS
2025-04-12T19:28:03.261254+00:00,BTCUSD,SELL,100,SUCCESS
2025-04-12T19:29:03.915164+00:00,BTCUSD,SELL,100,"ERROR: [Failure instance: Traceback: <class 'Exception'>: Cuenta no autorizada. Reiniciando autenticación.
/home/ubuntu/OpenApiPy/ctrader_open_api/factory.py:15:received
/home/ubuntu/OpenApiPy/ctrader_open_api/client.py:46:_received
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:877:callback
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:984:_startRunCallbacks
--- <exception caught here> ---
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:1078:_runCallbacks
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:304:process_order_response
]"
2025-04-12T19:30:02.915354+00:00,BTCUSD,BUY,100,"ERROR: [Failure instance: Traceback: <class 'Exception'>: Cuenta no autorizada. Reiniciando autenticación.
/home/ubuntu/OpenApiPy/ctrader_open_api/factory.py:15:received
/home/ubuntu/OpenApiPy/ctrader_open_api/client.py:46:_received
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:877:callback
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:984:_startRunCallbacks
--- <exception caught here> ---
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:1078:_runCallbacks
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:304:process_order_response
]"
2025-04-12T19:31:01.915192+00:00,BTCUSD,SELL,100,"ERROR: [Failure instance: Traceback: <class 'Exception'>: Cuenta no autorizada. Reiniciando autenticación.
/home/ubuntu/OpenApiPy/ctrader_open_api/factory.py:15:received
/home/ubuntu/OpenApiPy/ctrader_open_api/client.py:46:_received
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:877:callback
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:984:_startRunCallbacks
--- <exception caught here> ---
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:1078:_runCallbacks
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:304:process_order_response
]"
2025-04-12T19:32:01.915237+00:00,BTCUSD,SELL,100,"ERROR: [Failure instance: Traceback: <class 'Exception'>: Cuenta no autorizada. Reiniciando autenticación.
/home/ubuntu/OpenApiPy/ctrader_open_api/factory.py:15:received
/home/ubuntu/OpenApiPy/ctrader_open_api/client.py:46:_received
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:877:callback
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:984:_startRunCallbacks
--- <exception caught here> ---
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:1078:_runCallbacks
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:304:process_order_response
]"
2025-04-12T19:33:01.542539+00:00,BTCUSD,SELL,100,"ERROR: [Failure instance: Traceback: <class 'Exception'>: Cuenta no autorizada. Reiniciando autenticación.
/home/ubuntu/OpenApiPy/ctrader_open_api/factory.py:15:received
/home/ubuntu/OpenApiPy/ctrader_open_api/client.py:46:_received
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:877:callback
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:984:_startRunCallbacks
--- <exception caught here> ---
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:1078:_runCallbacks
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:304:process_order_response
]"
2025-04-12T19:34:01.542516+00:00,BTCUSD,SELL,100,"ERROR: [Failure instance: Traceback: <class 'Exception'>: Cuenta no autorizada. Reiniciando autenticación.
/home/ubuntu/OpenApiPy/ctrader_open_api/factory.py:15:received
/home/ubuntu/OpenApiPy/ctrader_open_api/client.py:46:_received
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:877:callback
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:984:_startRunCallbacks
--- <exception caught here> ---
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:1078:_runCallbacks
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:304:process_order_response
]"
2025-04-12T19:35:01.543425+00:00,BTCUSD,BUY,100,"ERROR: [Failure instance: Traceback: <class 'Exception'>: Cuenta no autorizada. Reiniciando autenticación.
/home/ubuntu/OpenApiPy/ctrader_open_api/factory.py:15:received
/home/ubuntu/OpenApiPy/ctrader_open_api/client.py:46:_received
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:877:callback
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:984:_startRunCallbacks
--- <exception caught here> ---
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:1078:_runCallbacks
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:304:process_order_response
]"
2025-04-12T19:36:01.541290+00:00,BTCUSD,BUY,100,"ERROR: [Failure instance: Traceback: <class 'Exception'>: Cuenta no autorizada. Reiniciando autenticación.
/home/ubuntu/OpenApiPy/ctrader_open_api/factory.py:15:received
/home/ubuntu/OpenApiPy/ctrader_open_api/client.py:46:_received
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:877:callback
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:984:_startRunCallbacks
--- <exception caught here> ---
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:1078:_runCallbacks
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:304:process_order_response
]"
2025-04-12T19:37:01.542224+00:00,BTCUSD,BUY,100,"ERROR: [Failure instance: Traceback: <class 'Exception'>: Cuenta no autorizada. Reiniciando autenticación.
/home/ubuntu/OpenApiPy/ctrader_open_api/factory.py:15:received
/home/ubuntu/OpenApiPy/ctrader_open_api/client.py:46:_received
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:877:callback
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:984:_startRunCallbacks
--- <exception caught here> ---
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:1078:_runCallbacks
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:304:process_order_response
]"
2025-04-12T19:38:01.543683+00:00,BTCUSD,SELL,100,"ERROR: [Failure instance: Traceback: <class 'Exception'>: Cuenta no autorizada. Reiniciando autenticación.
/home/ubuntu/OpenApiPy/ctrader_open_api/factory.py:15:received
/home/ubuntu/OpenApiPy/ctrader_open_api/client.py:46:_received
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:877:callback
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:984:_startRunCallbacks
--- <exception caught here> ---
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:1078:_runCallbacks
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:304:process_order_response
]"
2025-04-12T19:39:01.541866+00:00,BTCUSD,BUY,100,"ERROR: [Failure instance: Traceback: <class 'Exception'>: Cuenta no autorizada. Reiniciando autenticación.
/home/ubuntu/OpenApiPy/ctrader_open_api/factory.py:15:received
/home/ubuntu/OpenApiPy/ctrader_open_api/client.py:46:_received
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:877:callback
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:984:_startRunCallbacks
--- <exception caught here> ---
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:1078:_runCallbacks
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:304:process_order_response
]"
2025-04-12T19:40:01.543579+00:00,BTCUSD,SELL,100,"ERROR: [Failure instance: Traceback: <class 'Exception'>: Cuenta no autorizada. Reiniciando autenticación.
/home/ubuntu/OpenApiPy/ctrader_open_api/factory.py:15:received
/home/ubuntu/OpenApiPy/ctrader_open_api/client.py:46:_received
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:877:callback
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:984:_startRunCallbacks
--- <exception caught here> ---
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:1078:_runCallbacks
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:304:process_order_response
]"
2025-04-12T19:41:01.542596+00:00,BTCUSD,SELL,100,"ERROR: [Failure instance: Traceback: <class 'Exception'>: Cuenta no autorizada. Reiniciando autenticación.
/home/ubuntu/OpenApiPy/ctrader_open_api/factory.py:15:received
/home/ubuntu/OpenApiPy/ctrader_open_api/client.py:46:_received
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:877:callback
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:984:_startRunCallbacks
--- <exception caught here> ---
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:1078:_runCallbacks
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:304:process_order_response
]"
2025-04-12T19:42:01.544385+00:00,BTCUSD,SELL,100,"ERROR: [Failure instance: Traceback: <class 'Exception'>: Cuenta no autorizada. Reiniciando autenticación.
/home/ubuntu/OpenApiPy/ctrader_open_api/factory.py:15:received
/home/ubuntu/OpenApiPy/ctrader_open_api/client.py:46:_received
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:877:callback
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:984:_startRunCallbacks
--- <exception caught here> ---
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:1078:_runCallbacks
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:304:process_order_response
]"
2025-04-12T19:43:02.026806+00:00,BTCUSD,BUY,100,SUCCESS
2025-04-12T19:44:02.027270+00:00,BTCUSD,SELL,100,SUCCESS
2025-04-12T19:45:02.027512+00:00,BTCUSD,SELL,100,SUCCESS
2025-04-12T19:46:02.027787+00:00,BTCUSD,SELL,100,SUCCESS
2025-04-12T19:47:02.028589+00:00,BTCUSD,SELL,100,SUCCESS
2025-04-12T19:48:03.027829+00:00,BTCUSD,BUY,100,SUCCESS
2025-04-12T19:49:02.027676+00:00,BTCUSD,BUY,100,SUCCESS
2025-04-12T19:50:01.421297+00:00,BTCUSD,BUY,100,SUCCESS
2025-04-12T19:51:01.421227+00:00,BTCUSD,SELL,100,SUCCESS
2025-04-12T19:52:01.420159+00:00,BTCUSD,SELL,100,SUCCESS
2025-04-12T19:53:04.420660+00:00,BTCUSD,BUY,100,SUCCESS
2025-04-12T19:54:01.421194+00:00,BTCUSD,SELL,100,SUCCESS
2025-04-12T19:55:01.922802+00:00,BTCUSD,BUY,100,SUCCESS
2025-04-12T19:56:00.924765+00:00,BTCUSD,SELL,1,SUCCESS
2025-04-12T19:57:01.924389+00:00,BTCUSD,BUY,1,SUCCESS
2025-04-12T19:58:01.931081+00:00,BTCUSD,BUY,1,SUCCESS
2025-04-12T19:59:01.922899+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-12T20:00:01.924869+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-12T20:01:01.851664+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-12T20:02:01.840287+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-12T20:03:01.845021+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-12T20:04:05.843196+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-12T20:05:01.847210+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-12T20:06:02.842353+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-12T20:07:00.845430+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-12T20:08:01.850911+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-12T20:09:01.850774+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-12T20:10:02.849472+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-12T20:11:00.844174+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-12T20:12:01.848049+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-12T20:13:00.851178+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-14T15:28:26.004873+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-14T15:32:50.008568+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-14T15:33:03.005687+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-14T15:34:08.999279+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-14T15:35:03.006189+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-14T15:36:11.005292+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-14T15:37:03.002508+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-14T15:39:21.005437+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-14T15:39:28.626487+00:00,US 30,SELL,1.0,"ERROR: [Failure instance: Traceback: <class 'Exception'>: ❌ El símbolo US 30 no está en la lista local. Añádelo a SYMBOLS.
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/base.py:695:run
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/base.py:705:mainLoop
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/base.py:1090:runUntilCurrent
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:271:send_order_when_ready
--- <exception caught here> ---
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:254:send_order_when_ready
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:175:send_market_order
]"
2025-04-14T15:40:17.452888+00:00,US 30,SELL,1.0,"ERROR: [Failure instance: Traceback: <class 'Exception'>: ❌ El símbolo US 30 no está en la lista local. Añádelo a SYMBOLS.
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/base.py:695:run
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/base.py:705:mainLoop
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/base.py:1090:runUntilCurrent
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:271:send_order_when_ready
--- <exception caught here> ---
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:254:send_order_when_ready
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:175:send_market_order
]"
2025-04-14T15:41:01.880165+00:00,US 30,SELL,1.0,"ERROR: [Failure instance: Traceback: <class 'Exception'>: ❌ El símbolo US 30 no está en la lista local. Añádelo a SYMBOLS.
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/base.py:695:run
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/base.py:705:mainLoop
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/base.py:1090:runUntilCurrent
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:271:send_order_when_ready
--- <exception caught here> ---
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:254:send_order_when_ready
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:175:send_market_order
]"
2025-04-14T15:41:02.999015+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-14T15:42:02.013772+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-14T15:42:07.460616+00:00,US 30,SELL,1.0,"ERROR: [Failure instance: Traceback: <class 'Exception'>: ❌ El símbolo US 30 no está en la lista local. Añádelo a SYMBOLS.
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/base.py:695:run
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/base.py:705:mainLoop
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/base.py:1090:runUntilCurrent
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:271:send_order_when_ready
--- <exception caught here> ---
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:254:send_order_when_ready
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:175:send_market_order
]"
2025-04-14T15:43:02.019324+00:00,US 30,SELL,1.0,"ERROR: [Failure instance: Traceback: <class 'Exception'>: ❌ El símbolo US 30 no está en la lista local. Añádelo a SYMBOLS.
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/base.py:695:run
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/base.py:705:mainLoop
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/base.py:1090:runUntilCurrent
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:271:send_order_when_ready
--- <exception caught here> ---
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:254:send_order_when_ready
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:175:send_market_order
]"
2025-04-14T15:43:03.005679+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-14T15:44:02.035950+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-14T15:45:05.699526+00:00,US 30,SELL,1.0,"ERROR: [Failure instance: Traceback: <class 'Exception'>: ❌ El símbolo US 30 no está en la lista local. Añádelo a SYMBOLS.
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/base.py:695:run
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/base.py:705:mainLoop
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/base.py:1090:runUntilCurrent
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:271:send_order_when_ready
--- <exception caught here> ---
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:254:send_order_when_ready
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:175:send_market_order
]"
2025-04-14T15:45:13.011476+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-14T15:46:03.359325+00:00,US 30,SELL,1.0,"ERROR: [Failure instance: Traceback: <class 'Exception'>: ❌ El símbolo US 30 no está en la lista local. Añádelo a SYMBOLS.
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/base.py:695:run
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/base.py:705:mainLoop
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/base.py:1090:runUntilCurrent
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:271:send_order_when_ready
--- <exception caught here> ---
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:254:send_order_when_ready
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:175:send_market_order
]"
2025-04-14T15:47:01.587507+00:00,US 30,SELL,1.0,"ERROR: [Failure instance: Traceback: <class 'Exception'>: ❌ El símbolo US 30 no está en la lista local. Añádelo a SYMBOLS.
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/base.py:695:run
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/base.py:705:mainLoop
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/base.py:1090:runUntilCurrent
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:271:send_order_when_ready
--- <exception caught here> ---
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:254:send_order_when_ready
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:175:send_market_order
]"
2025-04-14T15:47:05.007570+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-14T15:48:00.937785+00:00,US 30,SELL,1.0,"ERROR: [Failure instance: Traceback: <class 'Exception'>: ❌ El símbolo US 30 no está en la lista local. Añádelo a SYMBOLS.
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/base.py:695:run
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/base.py:705:mainLoop
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/base.py:1090:runUntilCurrent
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:271:send_order_when_ready
--- <exception caught here> ---
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:254:send_order_when_ready
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:175:send_market_order
]"
2025-04-14T15:48:35.005874+00:00,BTCUSD,SELL,1.0,SUCCESS
2025-04-14T15:49:02.009440+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-14T15:49:03.006425+00:00,BTCUSD,SELL,1.0,SUCCESS
2025-04-14T15:50:05.003480+00:00,BTCUSD,SELL,1.0,SUCCESS
2025-04-14T15:50:31.007333+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-14T15:51:03.005464+00:00,BTCUSD,SELL,1.0,SUCCESS
2025-04-14T15:51:04.001569+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-14T15:51:19.002875+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-14T15:52:03.008293+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-14T15:52:04.002562+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-14T15:53:02.005366+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-14T15:54:03.007985+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-14T15:55:04.005143+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-14T15:56:03.012741+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-14T15:57:02.001474+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-14T15:58:02.007227+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-14T15:59:02.022236+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-14T16:00:24.000912+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-14T16:01:03.002585+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-14T16:02:03.006033+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-14T16:03:02.006680+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-14T16:04:02.026498+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-14T16:05:05.001061+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-14T16:06:02.002573+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-14T16:07:02.003648+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-14T16:08:02.015254+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-14T16:09:02.017669+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-14T16:10:01.003282+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-14T16:11:02.007114+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-14T16:12:02.004355+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-14T16:13:02.009163+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-14T16:14:03.007754+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-14T16:15:06.001138+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-14T16:16:04.008083+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-14T16:17:02.008157+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-14T16:18:02.005876+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-14T16:19:02.005579+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-14T16:20:06.013366+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-14T16:21:02.010813+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-14T16:22:02.009094+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-14T16:23:01.008501+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-14T16:24:03.005700+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-14T16:25:05.000632+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-14T16:26:02.007132+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-14T16:27:02.003565+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-14T16:28:02.001772+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-14T16:29:02.011695+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-14T16:30:06.005434+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-14T16:31:05.005343+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-14T16:32:02.008657+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-14T16:33:02.005764+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-14T16:34:02.003213+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-14T16:35:04.002251+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-14T16:36:03.006822+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-14T16:37:02.031495+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-14T16:38:02.033956+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-14T16:39:02.003019+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-14T16:40:02.999319+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-14T16:41:02.008119+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-14T16:42:02.011582+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-14T16:43:02.000293+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-14T16:44:01.002499+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-14T16:45:05.005867+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-14T16:46:04.007132+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-14T16:47:02.003732+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-14T16:48:02.011993+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-14T16:49:02.004330+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-14T16:50:03.014241+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-14T16:51:03.003271+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-14T16:52:01.003518+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-14T16:53:02.008969+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-14T16:54:02.002892+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-14T16:55:03.001490+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-14T16:56:02.005026+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-14T16:57:01.998950+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-14T16:58:02.011769+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-14T16:59:02.002198+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-15T18:40:03.827203+00:00,BTCUSD,BUY,0.1,,,,"ERROR: [Failure instance: Traceback: <class 'UnboundLocalError'>: cannot access local variable 'process_new_order' where it is not associated with a value
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/base.py:695:run
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/base.py:705:mainLoop
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/base.py:1090:runUntilCurrent
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:782:send_order_when_ready
--- <exception caught here> ---
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:758:send_order_when_ready
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:643:send_market_order
]"
2025-04-15T18:41:02.099789+00:00,BTCUSD,SELL,0.1,,,,"ERROR: [Failure instance: Traceback: <class 'UnboundLocalError'>: cannot access local variable 'process_new_order' where it is not associated with a value
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/base.py:695:run
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/base.py:705:mainLoop
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/base.py:1090:runUntilCurrent
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:782:send_order_when_ready
--- <exception caught here> ---
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:758:send_order_when_ready
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:643:send_market_order
]"
2025-04-15T18:42:02.764439+00:00,BTCUSD,BUY,0.1,,,,"ERROR: [Failure instance: Traceback: <class 'UnboundLocalError'>: cannot access local variable 'process_new_order' where it is not associated with a value
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/base.py:695:run
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/base.py:705:mainLoop
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/base.py:1090:runUntilCurrent
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:782:send_order_when_ready
--- <exception caught here> ---
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:758:send_order_when_ready
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:643:send_market_order
]"
2025-04-15T18:47:01.568742+00:00,BTCUSD,BUY,0.1,,,,SUCCESS
2025-04-15T18:48:03.600980+00:00,BTCUSD,SELL,0.1,,,,SUCCESS
2025-04-15T18:49:02.563035+00:00,BTCUSD,SELL,0.1,,,,SUCCESS
2025-04-15T18:50:02.558249+00:00,BTCUSD,SELL,0.1,,,,SUCCESS
2025-04-15T18:51:02.568997+00:00,BTCUSD,SELL,0.1,,,,SUCCESS
2025-04-15T18:52:02.563958+00:00,BTCUSD,SELL,0.1,,,,SUCCESS
2025-04-15T18:53:01.570329+00:00,BTCUSD,SELL,0.1,,,,SUCCESS
2025-04-15T18:54:01.595746+00:00,BTCUSD,SELL,0.1,,,,SUCCESS
2025-04-15T18:55:02.574114+00:00,BTCUSD,SELL,0.1,,,,SUCCESS
2025-04-15T18:56:03.565695+00:00,BTCUSD,BUY,0.1,,,,SUCCESS
2025-04-15T18:57:02.568402+00:00,BTCUSD,SELL,0.1,,,,SUCCESS
2025-04-15T18:58:01.571300+00:00,BTCUSD,BUY,0.1,,,,SUCCESS
2025-04-15T18:59:01.565903+00:00,BTCUSD,SELL,0.1,,,,SUCCESS
2025-04-15T19:00:06.562934+00:00,BTCUSD,SELL,0.1,,,,SUCCESS
2025-04-15T19:01:04.577722+00:00,BTCUSD,SELL,0.1,,,,SUCCESS
2025-04-15T19:02:01.731713+00:00,BTCUSD,SELL,0.1,5.0,,,"ERROR: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.defer.FirstError'>: FirstError[#0, [Failure instance: Traceback: <class 'AttributeError'>: Assignment not allowed to repeated field ""symbolId"" in protocol message object.
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:733:send_market_order
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:610:process_new_order
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:291:pips_to_price
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:268:get_symbol_info
--- <exception caught here> ---
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:217:get_symbol_info
/home/ubuntu/env/lib/python3.12/site-packages/google/protobuf/internal/python_message.py:664:setter
]]
]"
2025-04-15T19:03:01.261868+00:00,BTCUSD,SELL,0.1,5.0,,,"ERROR: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.defer.FirstError'>: FirstError[#0, [Failure instance: Traceback: <class 'AttributeError'>: Assignment not allowed to repeated field ""symbolId"" in protocol message object.
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:733:send_market_order
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:610:process_new_order
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:291:pips_to_price
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:268:get_symbol_info
--- <exception caught here> ---
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:217:get_symbol_info
/home/ubuntu/env/lib/python3.12/site-packages/google/protobuf/internal/python_message.py:664:setter
]]
]"
2025-04-15T19:04:02.693716+00:00,BTCUSD,SELL,0.1,5.0,,,"ERROR: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.defer.FirstError'>: FirstError[#0, [Failure instance: Traceback: <class 'AttributeError'>: Assignment not allowed to repeated field ""symbolId"" in protocol message object.
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:733:send_market_order
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:610:process_new_order
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:291:pips_to_price
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:268:get_symbol_info
--- <exception caught here> ---
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:217:get_symbol_info
/home/ubuntu/env/lib/python3.12/site-packages/google/protobuf/internal/python_message.py:664:setter
]]
]"
2025-04-15T19:05:04.039170+00:00,BTCUSD,SELL,0.1,5.0,,,"ERROR: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.defer.FirstError'>: FirstError[#0, [Failure instance: Traceback: <class 'AttributeError'>: Assignment not allowed to repeated field ""symbolId"" in protocol message object.
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:733:send_market_order
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:610:process_new_order
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:291:pips_to_price
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:268:get_symbol_info
--- <exception caught here> ---
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:217:get_symbol_info
/home/ubuntu/env/lib/python3.12/site-packages/google/protobuf/internal/python_message.py:664:setter
]]
]"
2025-04-15T19:06:02.385560+00:00,BTCUSD,SELL,0.1,5.0,,,"ERROR: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.defer.FirstError'>: FirstError[#0, [Failure instance: Traceback: <class 'AttributeError'>: Assignment not allowed to repeated field ""symbolId"" in protocol message object.
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:733:send_market_order
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:610:process_new_order
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:291:pips_to_price
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:268:get_symbol_info
--- <exception caught here> ---
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:217:get_symbol_info
/home/ubuntu/env/lib/python3.12/site-packages/google/protobuf/internal/python_message.py:664:setter
]]
]"
2025-04-15T19:07:01.179756+00:00,BTCUSD,BUY,0.1,5.0,,,"ERROR: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.defer.FirstError'>: FirstError[#0, [Failure instance: Traceback: <class 'AttributeError'>: Assignment not allowed to repeated field ""symbolId"" in protocol message object.
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:733:send_market_order
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:610:process_new_order
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:291:pips_to_price
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:268:get_symbol_info
--- <exception caught here> ---
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:217:get_symbol_info
/home/ubuntu/env/lib/python3.12/site-packages/google/protobuf/internal/python_message.py:664:setter
]]
]"
2025-04-15T19:08:02.022076+00:00,BTCUSD,SELL,0.1,5.0,,,"ERROR: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.defer.FirstError'>: FirstError[#0, [Failure instance: Traceback: <class 'AttributeError'>: Assignment not allowed to repeated field ""symbolId"" in protocol message object.
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:733:send_market_order
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:610:process_new_order
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:291:pips_to_price
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:268:get_symbol_info
--- <exception caught here> ---
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:217:get_symbol_info
/home/ubuntu/env/lib/python3.12/site-packages/google/protobuf/internal/python_message.py:664:setter
]]
]"
2025-04-15T19:10:07.563354+00:00,BTCUSD,SELL,0.1,5.0,,,"ERROR: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.defer.FirstError'>: FirstError[#0, [Failure instance: Traceback: <class 'AttributeError'>: Assignment not allowed to repeated field ""symbolId"" in protocol message object.
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:733:send_market_order
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:610:process_new_order
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:291:pips_to_price
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:268:get_symbol_info
--- <exception caught here> ---
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:217:get_symbol_info
/home/ubuntu/env/lib/python3.12/site-packages/google/protobuf/internal/python_message.py:664:setter
]]
]"
2025-04-15T19:11:01.040389+00:00,BTCUSD,SELL,0.1,5.0,,,"ERROR: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.defer.FirstError'>: FirstError[#0, [Failure instance: Traceback: <class 'AttributeError'>: Assignment not allowed to repeated field ""symbolId"" in protocol message object.
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:733:send_market_order
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:610:process_new_order
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:291:pips_to_price
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:268:get_symbol_info
--- <exception caught here> ---
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:217:get_symbol_info
/home/ubuntu/env/lib/python3.12/site-packages/google/protobuf/internal/python_message.py:664:setter
]]
]"
2025-04-15T19:12:01.551847+00:00,BTCUSD,SELL,0.1,5.0,,,"ERROR: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.defer.FirstError'>: FirstError[#0, [Failure instance: Traceback: <class 'AttributeError'>: Assignment not allowed to repeated field ""symbolId"" in protocol message object.
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:733:send_market_order
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:610:process_new_order
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:291:pips_to_price
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:268:get_symbol_info
--- <exception caught here> ---
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:217:get_symbol_info
/home/ubuntu/env/lib/python3.12/site-packages/google/protobuf/internal/python_message.py:664:setter
]]
]"
2025-04-15T19:15:21.315031+00:00,BTCUSD,SELL,0.1,5.0,,,"ERROR: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.defer.FirstError'>: FirstError[#0, [Failure instance: Traceback: <class 'AttributeError'>: Assignment not allowed to repeated field ""symbolId"" in protocol message object.
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:745:send_market_order
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:622:process_new_order
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:291:pips_to_price
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:268:get_symbol_info
--- <exception caught here> ---
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:217:get_symbol_info
/home/ubuntu/env/lib/python3.12/site-packages/google/protobuf/internal/python_message.py:664:setter
]]
]"
2025-04-15T19:16:03.220208+00:00,BTCUSD,SELL,0.1,5.0,,,"ERROR: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.defer.FirstError'>: FirstError[#0, [Failure instance: Traceback: <class 'AttributeError'>: Assignment not allowed to repeated field ""symbolId"" in protocol message object.
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:745:send_market_order
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:622:process_new_order
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:291:pips_to_price
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:268:get_symbol_info
--- <exception caught here> ---
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:217:get_symbol_info
/home/ubuntu/env/lib/python3.12/site-packages/google/protobuf/internal/python_message.py:664:setter
]]
]"
2025-04-15T19:17:01.242443+00:00,BTCUSD,BUY,0.1,5.0,,,"ERROR: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.defer.FirstError'>: FirstError[#0, [Failure instance: Traceback: <class 'AttributeError'>: Assignment not allowed to repeated field ""symbolId"" in protocol message object.
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:745:send_market_order
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:622:process_new_order
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:291:pips_to_price
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:268:get_symbol_info
--- <exception caught here> ---
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:217:get_symbol_info
/home/ubuntu/env/lib/python3.12/site-packages/google/protobuf/internal/python_message.py:664:setter
]]
]"
2025-04-15T19:18:01.426075+00:00,BTCUSD,BUY,0.1,5.0,,,"ERROR: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.defer.FirstError'>: FirstError[#0, [Failure instance: Traceback: <class 'AttributeError'>: Assignment not allowed to repeated field ""symbolId"" in protocol message object.
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:745:send_market_order
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:622:process_new_order
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:291:pips_to_price
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:268:get_symbol_info
--- <exception caught here> ---
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:217:get_symbol_info
/home/ubuntu/env/lib/python3.12/site-packages/google/protobuf/internal/python_message.py:664:setter
]]
]"
2025-04-15T19:19:00.890988+00:00,BTCUSD,BUY,0.1,5.0,,,"ERROR: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.defer.FirstError'>: FirstError[#0, [Failure instance: Traceback: <class 'AttributeError'>: Assignment not allowed to repeated field ""symbolId"" in protocol message object.
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:745:send_market_order
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:622:process_new_order
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:291:pips_to_price
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:268:get_symbol_info
--- <exception caught here> ---
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:217:get_symbol_info
/home/ubuntu/env/lib/python3.12/site-packages/google/protobuf/internal/python_message.py:664:setter
]]
]"
2025-04-15T19:20:03.038286+00:00,BTCUSD,BUY,0.1,5.0,,,"ERROR: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.defer.FirstError'>: FirstError[#0, [Failure instance: Traceback: <class 'AttributeError'>: Assignment not allowed to repeated field ""symbolId"" in protocol message object.
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:745:send_market_order
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:622:process_new_order
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:291:pips_to_price
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:268:get_symbol_info
--- <exception caught here> ---
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:217:get_symbol_info
/home/ubuntu/env/lib/python3.12/site-packages/google/protobuf/internal/python_message.py:664:setter
]]
]"
2025-04-15T19:21:00.813285+00:00,BTCUSD,BUY,0.1,5.0,,,"ERROR: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.defer.FirstError'>: FirstError[#0, [Failure instance: Traceback: <class 'AttributeError'>: Assignment not allowed to repeated field ""symbolId"" in protocol message object.
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:745:send_market_order
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:622:process_new_order
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:291:pips_to_price
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:268:get_symbol_info
--- <exception caught here> ---
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:217:get_symbol_info
/home/ubuntu/env/lib/python3.12/site-packages/google/protobuf/internal/python_message.py:664:setter
]]
]"
2025-04-15T19:22:01.537497+00:00,BTCUSD,SELL,0.1,5.0,,,"ERROR: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.defer.FirstError'>: FirstError[#0, [Failure instance: Traceback: <class 'AttributeError'>: Assignment not allowed to repeated field ""symbolId"" in protocol message object.
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:745:send_market_order
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:622:process_new_order
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:291:pips_to_price
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:268:get_symbol_info
--- <exception caught here> ---
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:217:get_symbol_info
/home/ubuntu/env/lib/python3.12/site-packages/google/protobuf/internal/python_message.py:664:setter
]]
]"
2025-04-15T19:23:01.350029+00:00,BTCUSD,BUY,0.1,5.0,,,"ERROR: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.defer.FirstError'>: FirstError[#0, [Failure instance: Traceback: <class 'AttributeError'>: Assignment not allowed to repeated field ""symbolId"" in protocol message object.
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:745:send_market_order
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:622:process_new_order
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:291:pips_to_price
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:268:get_symbol_info
--- <exception caught here> ---
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:217:get_symbol_info
/home/ubuntu/env/lib/python3.12/site-packages/google/protobuf/internal/python_message.py:664:setter
]]
]"
2025-04-15T19:30:32.914302+00:00,BTCUSD,BUY,0.1,5.0,,,"ERROR: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.defer.FirstError'>: FirstError[#0, [Failure instance: Traceback: <class 'AttributeError'>: Assignment not allowed to repeated field ""symbolId"" in protocol message object.
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:745:send_market_order
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:622:process_new_order
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:291:pips_to_price
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:268:get_symbol_info
--- <exception caught here> ---
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:217:get_symbol_info
/home/ubuntu/env/lib/python3.12/site-packages/google/protobuf/internal/python_message.py:664:setter
]]
]"
2025-04-15T19:34:00.939272+00:00,BTCUSD,SELL,0.1,5.0,,,"ERROR: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.defer.FirstError'>: FirstError[#0, [Failure instance: Traceback: <class 'AttributeError'>: Assignment not allowed to repeated field ""symbolId"" in protocol message object.
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:745:send_market_order
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:622:process_new_order
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:291:pips_to_price
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:268:get_symbol_info
--- <exception caught here> ---
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:217:get_symbol_info
/home/ubuntu/env/lib/python3.12/site-packages/google/protobuf/internal/python_message.py:664:setter
]]
]"
2025-04-15T19:35:01.294132+00:00,BTCUSD,SELL,0.1,,,,SUCCESS
2025-04-15T19:50:11.733431+00:00,BTCUSD,SELL,0.1,,,,SUCCESS
2025-04-15T19:51:02.737524+00:00,BTCUSD,BUY,0.1,,,,SUCCESS
2025-04-15T19:52:01.729921+00:00,BTCUSD,BUY,0.1,,,,SUCCESS
2025-04-15T19:55:04.861792+00:00,BTCUSD,BUY,0.1,,,,SUCCESS
2025-04-15T19:56:03.851141+00:00,BTCUSD,BUY,0.1,,,,SUCCESS
2025-04-15T19:57:08.093292+00:00,BTCUSD,SELL,0.1,,,,SUCCESS
2025-04-15T19:58:03.096054+00:00,BTCUSD,SELL,0.1,,,,SUCCESS
2025-04-15T20:05:02.482242+00:00,BTCUSD,SELL,0.1,,,,SUCCESS
2025-04-15T20:07:06.530582+00:00,BTCUSD,BUY,0.1,,,,"ERROR: [Failure instance: Traceback: <class 'twisted.internet.defer.TimeoutError'>: (5, 'Deferred')
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:798:timeItOut
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:957:cancel
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:916:errback
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:984:_startRunCallbacks
--- <exception caught here> ---
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:1078:_runCallbacks
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:809:convertCancelled
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:293:_cancelledToTimedOutError
]"
2025-04-15T20:08:19.083119+00:00,BTCUSD,SELL,0.1,,,,"ERROR: [Failure instance: Traceback: <class 'twisted.internet.defer.TimeoutError'>: (5, 'Deferred')
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:798:timeItOut
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:957:cancel
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:916:errback
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:984:_startRunCallbacks
--- <exception caught here> ---
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:1078:_runCallbacks
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:809:convertCancelled
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:293:_cancelledToTimedOutError
]"
2025-04-15T20:09:07.656426+00:00,BTCUSD,BUY,0.1,,,,"ERROR: [Failure instance: Traceback: <class 'twisted.internet.defer.TimeoutError'>: (5, 'Deferred')
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:798:timeItOut
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:957:cancel
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:916:errback
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:984:_startRunCallbacks
--- <exception caught here> ---
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:1078:_runCallbacks
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:809:convertCancelled
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:293:_cancelledToTimedOutError
]"
2025-04-15T20:10:02.972252+00:00,BTCUSD,BUY,0.1,,,,"ERROR: [Failure instance: Traceback: <class 'twisted.internet.defer.TimeoutError'>: (5, 'Deferred')
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:798:timeItOut
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:957:cancel
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:916:errback
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:984:_startRunCallbacks
--- <exception caught here> ---
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:1078:_runCallbacks
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:809:convertCancelled
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:293:_cancelledToTimedOutError
]"
2025-04-15T20:11:02.617025+00:00,BTCUSD,BUY,0.1,,,,"ERROR: [Failure instance: Traceback: <class 'twisted.internet.defer.TimeoutError'>: (5, 'Deferred')
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:798:timeItOut
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:957:cancel
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:916:errback
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:984:_startRunCallbacks
--- <exception caught here> ---
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:1078:_runCallbacks
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:809:convertCancelled
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:293:_cancelledToTimedOutError
]"
2025-04-15T20:12:08.838987+00:00,BTCUSD,BUY,0.1,,,,"ERROR: [Failure instance: Traceback: <class 'twisted.internet.defer.TimeoutError'>: (5, 'Deferred')
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:798:timeItOut
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:957:cancel
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:916:errback
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:984:_startRunCallbacks
--- <exception caught here> ---
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:1078:_runCallbacks
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:809:convertCancelled
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:293:_cancelledToTimedOutError
]"
2025-04-15T20:33:01.271118+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-15T20:34:01.267408+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-15T20:35:02.268820+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-15T20:36:01.268919+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-15T20:37:02.271990+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-15T20:38:02.272341+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-15T20:39:01.265206+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-15T20:40:02.289670+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-15T20:41:01.271342+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-15T20:42:02.266051+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-15T20:43:01.269935+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-15T20:48:02.666313+00:00,ALL,CLOSE,0,"ERROR: [Failure instance: Traceback: <class 'AttributeError'>: 'ProtoMessage' object has no attribute 'position'
/home/ubuntu/OpenApiPy/ctrader_open_api/factory.py:15:received
/home/ubuntu/OpenApiPy/ctrader_open_api/client.py:46:_received
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:877:callback
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:984:_startRunCallbacks
--- <exception caught here> ---
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:1078:_runCallbacks
/home/ubuntu/tradingview-ctrader-webhook/henry-webhook-v6.py:52:handle_positions
]"
2025-04-15T20:48:04.673154+00:00,BTCUSD,SELL,0.1,SUCCESS (after close error)
2025-04-15T20:49:06.074186+00:00,ALL,CLOSE,0,"ERROR: [Failure instance: Traceback: <class 'twisted.internet.defer.TimeoutError'>: (5, 'Deferred')
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:798:timeItOut
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:957:cancel
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:916:errback
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:984:_startRunCallbacks
--- <exception caught here> ---
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:1078:_runCallbacks
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:809:convertCancelled
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:293:_cancelledToTimedOutError
]"
2025-04-15T20:49:11.075691+00:00,BTCUSD,SELL,0.1,"ERROR: [Failure instance: Traceback: <class 'twisted.internet.defer.TimeoutError'>: (5, 'Deferred')
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:798:timeItOut
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:957:cancel
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:916:errback
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:984:_startRunCallbacks
--- <exception caught here> ---
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:1078:_runCallbacks
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:809:convertCancelled
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:293:_cancelledToTimedOutError
]"
2025-04-15T20:52:01.496275+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-15T20:53:03.494735+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-15T20:54:01.490098+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-15T20:55:02.499806+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-15T20:56:01.527928+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-15T20:57:01.497498+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-15T20:58:02.494775+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-15T21:07:20.658687+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-15T21:08:16.829978+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-15T21:09:08.160161+00:00,BTCUSD,SELL,0.1,"ERROR: [Failure instance: Traceback: <class 'twisted.internet.defer.TimeoutError'>: (5, 'Deferred')
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:798:timeItOut
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:957:cancel
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:916:errback
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:984:_startRunCallbacks
--- <exception caught here> ---
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:1078:_runCallbacks
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:809:convertCancelled
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:293:_cancelledToTimedOutError
]"
2025-04-15T21:10:07.136401+00:00,BTCUSD,SELL,0.1,"ERROR: [Failure instance: Traceback: <class 'twisted.internet.defer.TimeoutError'>: (5, 'Deferred')
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:798:timeItOut
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:957:cancel
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:916:errback
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:984:_startRunCallbacks
--- <exception caught here> ---
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:1078:_runCallbacks
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:809:convertCancelled
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:293:_cancelledToTimedOutError
]"
2025-04-15T21:11:08.766188+00:00,BTCUSD,BUY,0.1,"ERROR: [Failure instance: Traceback: <class 'twisted.internet.defer.TimeoutError'>: (5, 'Deferred')
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:798:timeItOut
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:957:cancel
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:916:errback
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:984:_startRunCallbacks
--- <exception caught here> ---
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:1078:_runCallbacks
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:809:convertCancelled
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/defer.py:293:_cancelledToTimedOutError
]"
2025-04-15T21:17:39.504584+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-15T21:18:24.970707+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-15T21:20:01.844535+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-15T21:21:00.840459+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-15T21:22:02.839541+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-15T21:23:01.840573+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-15T21:24:00.836943+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-15T21:25:01.836090+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-15T21:26:08.844318+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-15T21:27:01.844464+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-15T21:28:01.838402+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-15T21:29:01.840469+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-15T21:30:01.837618+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-15T21:31:01.844509+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-15T21:32:01.836816+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-15T21:33:01.842485+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-15T21:34:01.841656+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-15T21:35:02.842935+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-15T21:36:01.837916+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-15T21:37:01.839875+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-15T21:38:01.839538+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-15T21:39:01.840843+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-15T21:40:01.841911+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-15T21:41:01.842216+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-15T21:42:01.835545+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-15T21:43:01.844809+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-15T21:44:01.840019+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-15T21:45:02.843680+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-15T21:46:01.838132+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-15T21:47:01.843192+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-15T21:48:02.843648+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-15T21:49:04.841181+00:00,BTCUSD,BUY,0.1,SUCCESS
2025-04-15T21:50:01.836173+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-15T21:51:01.835335+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-15T21:52:01.835668+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-15T21:53:01.842394+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-15T21:54:01.834508+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-15T21:55:01.841743+00:00,BTCUSD,SELL,0.1,SUCCESS
2025-04-15T22:08:08.301346+00:00,BTCUSD,BUY,0.1,"ERROR: [Failure instance: Traceback: <class 'NameError'>: name 'account_id' is not defined
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/base.py:705:mainLoop
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/base.py:1090:runUntilCurrent
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:249:send_order_when_ready
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:202:send_market_order
--- <exception caught here> ---
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:179:send_market_order
]"
2025-04-15T22:09:00.933042+00:00,BTCUSD,SELL,0.1,1.0,3.0,"ERROR: [Failure instance: Traceback: <class 'NameError'>: name 'account_id' is not defined
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/base.py:705:mainLoop
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/base.py:1090:runUntilCurrent
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:249:send_order_when_ready
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:202:send_market_order
--- <exception caught here> ---
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:179:send_market_order
]"
2025-04-15T22:10:01.848423+00:00,BTCUSD,SELL,0.1,1.0,3.0,"ERROR: [Failure instance: Traceback: <class 'NameError'>: name 'account_id' is not defined
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/base.py:705:mainLoop
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/base.py:1090:runUntilCurrent
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:249:send_order_when_ready
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:202:send_market_order
--- <exception caught here> ---
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:179:send_market_order
]"
2025-04-15T22:11:00.869445+00:00,BTCUSD,BUY,0.1,1.0,3.0,"ERROR: [Failure instance: Traceback: <class 'NameError'>: name 'account_id' is not defined
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/base.py:705:mainLoop
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/base.py:1090:runUntilCurrent
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:249:send_order_when_ready
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:202:send_market_order
--- <exception caught here> ---
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:179:send_market_order
]"
2025-04-15T22:15:03.344321+00:00,BTCUSD,SELL,0.1,1.0,3.0,"ERROR: [Failure instance: Traceback: <class 'AttributeError'>: 'Client' object has no attribute 'open_market_sell'
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/base.py:705:mainLoop
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/base.py:1090:runUntilCurrent
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:249:send_order_when_ready
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:202:send_market_order
--- <exception caught here> ---
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:197:send_market_order
]"
2025-04-15T22:17:01.313015+00:00,BTCUSD,SELL,0.1,1.0,3.0,"ERROR: [Failure instance: Traceback: <class 'ImportError'>: cannot import name 'ProtoOATradeSide' from 'ctrader_open_api.messages.OpenApiCommonMessages_pb2' (/home/ubuntu/OpenApiPy/ctrader_open_api/messages/OpenApiCommonMessages_pb2.py)
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/base.py:705:mainLoop
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/base.py:1090:runUntilCurrent
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:271:send_order_when_ready
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:214:send_market_order
--- <exception caught here> ---
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:180:send_market_order
]"
2025-04-15T22:18:01.518123+00:00,BTCUSD,BUY,0.1,1.0,3.0,"ERROR: [Failure instance: Traceback: <class 'ImportError'>: cannot import name 'ProtoOATradeSide' from 'ctrader_open_api.messages.OpenApiCommonMessages_pb2' (/home/ubuntu/OpenApiPy/ctrader_open_api/messages/OpenApiCommonMessages_pb2.py)
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/base.py:705:mainLoop
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/base.py:1090:runUntilCurrent
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:271:send_order_when_ready
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:214:send_market_order
--- <exception caught here> ---
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:180:send_market_order
]"
2025-04-15T22:19:01.593448+00:00,BTCUSD,SELL,0.1,1.0,3.0,"ERROR: [Failure instance: Traceback: <class 'ImportError'>: cannot import name 'ProtoOATradeSide' from 'ctrader_open_api.messages.OpenApiCommonMessages_pb2' (/home/ubuntu/OpenApiPy/ctrader_open_api/messages/OpenApiCommonMessages_pb2.py)
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/base.py:705:mainLoop
/home/ubuntu/env/lib/python3.12/site-packages/twisted/internet/base.py:1090:runUntilCurrent
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:271:send_order_when_ready
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:214:send_market_order
--- <exception caught here> ---
/home/ubuntu/tradingview-ctrader-webhook/ctrader.py:180:send_market_order
]"
